#--------------------------------------------------------------------------
# set Working Directory
#--------------------------------------------------------------------------
setwd('/home/waseem/Documents/Self-Development/git_repos/waseem-self-development/Online Retail II UCI/')


#--------------------------------------------------------------------------
# Load libraries
#--------------------------------------------------------------------------
library(data.table)
library(ggplot2)
library(tidyverse)
library(lubridate)


#--------------------------------------------------------------------------
# load dataset
#--------------------------------------------------------------------------

# we'll load the csv from our location
raw_dataset <- data.table(
	read.csv('/home/waseem/Documents/Self-Development/Online Retail II UCI/online_retail_II.csv', 
		stringsAsFactors = F)
)

#--------------------------------------------------------------------------
# clean dataset
#--------------------------------------------------------------------------

# create new DF, so we can revert back to this if we mess up
# saves us having to load the data into R again
# good practice for when we have large datasets which take time to load in
# or datasets which incur costs (such as loading in from BigQuery)
# we'll also change column names, personal preference as it makes it 
# quicker/easier for me to type out whilst i'm coding
dataset <- data.table(
	raw_dataset %>%
		rename(
			invoice_id = Invoice,
			stock_code = StockCode,
			description = Description,
			qty = Quantity,
			invoice_timestamp = InvoiceDate,
			price = Price,
			customer_id = Customer.ID,
			country = Country
		)
)

# lets check the structure of the dataset, to see if we need to change
# column types (e.g. string values into numeric etc)
str(dataset)
# the only columns which needs attention are invoice_timestamp and customer_id
# we need to change their column types
# we'll also feature engineer a product_revenue column
# this will be price x qty

dataset <- data.table(
		dataset %>%
			# first let's feature engineer a pure date column from invoice_timestamp
			# this just makes it easier later on to have them seperate
			# we'll then convert invoice_timestamp from string to timestamp
			# we'll convert customer_id into string
			mutate(
				invoice_date = ymd(substr(invoice_timestamp, 1, 10)),
				invoice_timestamp = ymd_hms(invoice_timestamp),
				customer_id = as.character(customer_id),
				product_revenue = price * qty
			)
)



# we'll run a summary over our dataset to understand it better
summary(dataset)
# look to see if we have any oddities/nulls in our dataset
sapply(dataset, function(x) sum(is.na(x)))
# Apart from customer_id, all our string columns don't have nulls
# we have 243007 nulls in the customer_id column (23% of all records)
# we also have negative values in qty and price columns
# our dataset date range is from 1st of Dec 2009 to 9th Dec 2011


# let's try and understand our nulls in customer_id
# we'll create a new dataframe for this, so we don't mess up our orginal dataset
customer_id_nulls <- data.table(
	dataset %>%
		# we'll create a new column as a flag it the row has a customer_id or is null
		mutate(has_customer_id = ifelse(is.na(customer_id) == F, 'yes', 'no'))
)
# we'll look to see how much revenue is generated by null customer_id's
customer_id_nulls_revenue <- data.table(
	customer_id_nulls %>%
		group_by(has_customer_id) %>%
		summarise(product_revenue = sum(product_revenue)) %>%
		ungroup() %>%
		mutate(percent = product_revenue/sum(product_revenue))
) %>% 
		ggplot(aes(x = has_customer_id, y = percent, fill = has_customer_id)) +
		geom_bar(stat = 'identity') +
		ggtitle('% of Total Revenue', 
						'From orders with customer_id vs without customer_id') +
		labs(x = 'Do we have a customer_id?', y = '% of Total Revenue') +
		# text for the conversion
		geom_text(aes(label = paste0(round(percent * 100), '%')), 
		          color = 'white', size = 4, fontface = 'bold',
		          position = position_stack(vjust = 0.5, reverse = FALSE)) +
		# gives the y axis the percentage scale
		scale_y_continuous(labels = scales::percent) +
		# we don't want a legend for the fill
		guides(fill = 'none')
# revenue from null customer_ids make up 14% of revenue
# we'll keep them in for revenue analysis, but we'll remove for any
# dedicated customer analysis


#--------------------------------------------------------------------------
# EDA visualisations
#--------------------------------------------------------------------------

# now that we're happy with our dataset, we'll conduct some EDA



# ----------------- revenue per country
revenue_per_country <- data.table(
	dataset %>%
		group_by(country) %>%
		summarise(revenue = sum(product_revenue)) %>%
		ungroup() %>%
		mutate(percent = revenue / sum(revenue)) %>%
		arrange(-percent)
) %>%
	ggplot(aes(x = reorder(country, revenue), y = revenue, fill = percent)) +
	geom_bar(stat = 'identity') +
	ggtitle('Revenue by Country',
					'The UK is by far the biggest market') +
	labs(x = 'Country', y = '£') +
	# text for the conversion
	geom_text(aes(label = ifelse(percent > 0.8,
									paste0(round(percent * 100), '%'),'')), 
	          color = 'white', size = 4, fontface = 'bold',
	          position = position_stack(vjust = 0.5, reverse = FALSE)) +
	# gives the y axis the percentage scale
	scale_y_continuous(labels = scales::comma) +
	# we don't want a legend for the fill
	guides(fill = 'none') +
	coord_flip() 


# ----------------- revenue per country (minus UK)
# we'll look at percentage of revenue of countries minus UK
revenue_per_country_minus_UK <- data.table(
	dataset %>%
		filter(country != 'United Kingdom') %>%
		group_by(country) %>%
		summarise(revenue = sum(product_revenue)) %>%
		ungroup() %>%
		mutate(percent = revenue / sum(revenue)) %>%
		arrange(-percent)
) %>%
	ggplot(aes(x = reorder(country, revenue), y = revenue, fill = percent)) +
	geom_bar(stat = 'identity') +
	ggtitle('Revenue by Country',
					'Without the UK') +
	labs(x = 'Country', y = '£') +
	# text for the conversion
	geom_text(aes(label = ifelse(percent > 0.01,
									paste0(round(percent * 100), '%'),'')), 
	          color = 'white', size = 4, fontface = 'bold',
	          position = position_stack(vjust = 0.5, reverse = FALSE)) +
	# gives the y axis the percentage scale
	scale_y_continuous(labels = scales::comma) +
	# we don't want a legend for the fill
	guides(fill = 'none') +
	coord_flip() 


# AOV by country
# orders by country
# % revenue minus UK
# total customers by country
# revenue by year